---
name: CI
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  # Check if there any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: latest

  tests-on-windows:
    needs: golangci-lint # run after golangci-lint action to not produce duplicated errors
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15 # test only the latest go version to speed up CI
      - name: Run tests
        run: go test ./...
        continue-on-error: true
  tests-on-macos:
    needs: golangci-lint # run after golangci-lint action to not produce duplicated errors
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15 # test only the latest go version to speed up CI
      - name: Run tests
        run: make test
  tests-on-unix:
    needs: golangci-lint # run after golangci-lint action to not produce duplicated errors
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Run tests
        run: make test
  coverage:
    needs: golangci-lint # run after golangci-lint action to not produce duplicated errors
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: coverage-${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            coverage-${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Run tests with coverage
        run: make coverage
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
